### ISSUE TITLE
gwt:devmode is not recompiling sub modules

### ISSUE THREAD

**Issue by NightFox7** [tbroyer/gwt-maven-plugin#107]
I don't know if this is an issue or I misunderstood how this plugin should work but i am really struggling here. I was using the eclipse plugin to run my gwt app in super dev mode. Now i switched to Intellij and i am trying to use the maven gwt:devmode for development however due to the fact that my project has multiple maven module with one main module that contains all the entry points,  it seems that the incremental compilation does not work when i modify a submodule. Only a mvn package in the submodule and the main module and restart of gwt:devmode allows me to see my changes. Is this how is it supposed to work or am i doing something wrong here. Thank you for your help.

PS i just migrated from the mojo maven plugin

**Comment by tbroyer** [comment]
Are you running `gwt:devmode` (you should really switch to `gwt:codeserver` BTW) from the root/aggregator module? This is how you're supposed to use this plugin.

**Comment by NightFox7** [comment]
Yes that's indeed what I am doing, I run gwt:devmode on the main module where I have all the dependencies to the submodules. (I also tried using gwt:codeserver and jetty but I keep getting Failed 
```
startup of context o.e.j.w.WebAppContext 
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:647)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1305)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1271)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1167)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.eclipse.jetty.xml.XmlParser.parse(XmlParser.java:252)
	at org.eclipse.jetty.webapp.Descriptor.parse(Descriptor.java:54)
	at org.eclipse.jetty.webapp.WebDescriptor.parse(WebDescriptor.java:207)
	at org.eclipse.jetty.webapp.MetaData.setWebXml(MetaData.java:196)
	at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:60)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:468)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:504)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at fr.gefco.tli.psc.dev.helper.MainHelper.createPortalJetty(MainHelper.java:407)
```

**Comment by tbroyer** [comment]
If you run `gwt:devmode` (or `gwt:codeserver`) at the gwt-app / war level, then your (Maven) dependencies are loaded as JARs (from your local Maven repo where you `mvn install`ed them); that's just how Maven works.
In a multi-module Maven project, you need to run `gwt:devmode` on the root/aggregator Maven module (the one with with `<type>pom</type>` and `<modules>` for your submodules), configuring the `warDir` to point to where a `mvn package` will have created your exploded WAR (e.g. `mywebapp/target/mywebapp-1.0.0-SNAPSHOT`, or `mywebapp/target/mywebapp-${project.version}`)

See https://tbroyer.github.io/gwt-maven-plugin/codeserver.html, and https://github.com/tbroyer/gwt-maven-archetypes/ for examples.

Fwiw, the stacktrace you posted is related to the `<!DOCTYPE` in your `WEB-INF/web.xml` that Jetty apparently tries to load (and fail). Try removing it.

**Comment by NightFox7** [comment]
I think I understand better now so I added this to the root module
```
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>1.0-rc-9</version>
                <extensions>true</extensions>
            </plugin>
```
and I run mvn gwt:devmode

This time I got "No projet found" error

**Comment by tbroyer** [comment]
cf. https://tbroyer.github.io/gwt-maven-plugin/devmode-mojo.html#projects (which you can pass as a property on the command-line)

**Comment by NightFox7** [comment]
Thank you for your fast replies

Now I am getting 
```
 neither a gwt-lib or jar:sources; Did you forget to use <type>gwt-lib</type> in the dependency declaration?
```
of all my submodules and then the compilation fails with 
```
portal-4.3-SNAPSHOT) cannot contain any of the following characters:
[ERROR] : * ? " < > |
```
The work folder of the root module is empty

**Comment by tbroyer** [comment]
> Now I am getting
> 
>      neither a gwt-lib or jar:sources; Did you forget to use <type>gwt-lib</type> in the dependency declaration?
> of all my submodules

See https://github.com/tbroyer/gwt-maven-plugin/issues/31

Fwiw, if you'd like to contribute improvements to https://tbroyer.github.io/gwt-maven-plugin/migrating.html after that (maybe a kind of step-by-step instructions), patches are welcome.

**Comment by NightFox7** [comment]
Yes I would be happy to contribute. From my perspective, I still don't quite understand the purpose of `<type>gwt-lib</type>` as well as the packaging type (gwt-lib, gwt-app)

For my case, for example, the gwt-lib did not work but the classifier sources did the trick like you said. Perhaps this should be added to the instructions.

Now I am facing the problem : 
```
impossible de trouver ou charger la classe principale com.google.gwt.dev.codeserver.CodeServer
```

even though I do have all the required dependencies
```
<dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-dev</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.gwt</groupId>
            <artifactId>gwt-codeserver</artifactId>
            <scope>provided</scope>
        </dependency>
```

**Comment by tbroyer** [comment]
From https://tbroyer.github.io/gwt-maven-plugin/codeserver.html:
> Also, dependencies by default use the `runtime` scope, whereas `gwt:compile` uses the `compile` scope; this allows some differences between `gwt:compile` and `gwt:codeserver` classpaths when needed, while working in identical ways most of the time (where dependencies are put in the default `compile` scope). In any case, that behavior is configurable through the `classpathScope` property.

https://tbroyer.github.io/gwt-maven-plugin/devmode-mojo.html#classpathScope

Re.
> I still don't quite understand the purpose of `<type>gwt-lib</type>` as well as the packaging type (gwt-lib, gwt-app)

`gwt-lib` type in a dependency means that it's a JAR that contains Java sources. The `gwt:devmode` and `gwt:codeserver` use them as a trigger that they need to use the dependent submodule's compile source roots (`src/main/java`, `generated-sources/annotations`, etc.) to the classpath, in addition to the `target/classes`, so you can just edit your Java file and reload your page to see the result (other kinds of changes, such as to `src/main/resources` require running some Maven goals, e.g. `resources:resources`). See https://tbroyer.github.io/gwt-maven-plugin/artifact-handlers.html

The `gwt-lib` and `gwt-app` packaging types automatically bind plugin goals to specific phases: https://tbroyer.github.io/gwt-maven-plugin/lifecycles.html

**Comment by NightFox7** [comment]
I understand better now and I added `<classpathScope>compile+runtime</classpathScope>` and now it finally works !

But I am still not sure if I am using the plugin correctly in the sub modules.
With the old plugin I used to have
```
		<plugin>
			<groupId>org.codehaus.mojo</groupId>
			<artifactId>gwt-maven-plugin</artifactId>
			<executions>
				<execution>
					<goals>
						<goal>resources</goal>
					</goals>
				</execution>
			</executions>
		</plugin>
```
Now I replaced this with 
```
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <configuration>
                    <moduleName>MyModule</moduleName>
                </configuration>
            </plugin>
```

Is this how it is supposed to be done?

Also some of my maven modules contain 2 gwt modules. In this case should I also add the execution tag with the second gwt module ? BTW isn't it simpler to put all the modules in the configuration tag ?

**Comment by NightFox7** [comment]
And there's another problem I am facing, Some of my submodules do not have an entrypoint. This causes the gwt compile to fail. What do you think I should do in this case ?

**Comment by tbroyer** [comment]
> But I am still not sure if I am using the plugin correctly in the sub modules.
> With the old plugin I used to have
> […some snippet with `gwt:resources`…]
> Now I replaced this with
> […some snippet with no execution…]
> Is this how it is supposed to be done?

There's no equivalent to Mojo's `gwt:resources` in this plugin. Also notice how this goal is itself deprecated: https://gwt-maven-plugin.github.io/gwt-maven-plugin/resources-mojo.html Use the suggested replacement; or use the `gwt-lib` packaging, which will use [`gwt:package-lib`](https://tbroyer.github.io/gwt-maven-plugin/package-lib-mojo.html) instead of `jar:jar` to package the library (among other things; review the lifecycle at https://tbroyer.github.io/gwt-maven-plugin/lifecycles.html and compare it with the standard `jar` lifecycle –linked from that page).

> Also some of my maven modules contain 2 gwt modules. In this case should I also add the execution tag with the second gwt module ?

You can skip the `gwt:generate-module` and `gwt:generate-module-metadata` goals by setting `skipModule` and `skipModuleMetadata` properties to `true`.

To be fair, I still don't know if I like those goals and whether they should be enabled by default; and this is basically the one thing refraining me from cutting a 1.0.

If you're talking about a module containing two GWT applications, then yes you'd have to have 2 executions of the `gwt:compile` goal.

See #57 

> And there's another problem I am facing, Some of my submodules do not have an entrypoint. This causes the gwt compile to fail. What do you think I should do in this case ?

The `projects` and `modules` properties of `gwt:devmode` and `gwt:codeserver` should only point to GWT application modules.
Library modules should not be passed to any of `gwt:devmode`, `gwt:codeserver`, or `gwt:compile`.

**Comment by NightFox7** [comment]
> If you're talking about a module containing two GWT applications, then yes you'd have to have 2 executions of the gwt:compile goal.

Actually I noticed that when I add 2 executions the plugin compiles twice the module I put in 'moduleName' therefore I only added one execution.

For my submodules, I ended up removing the plugin and the packaging `gwt-lib` it seems that adding the dependency with the classifier <sources> suffice. 

I even removed the packaging `gwt-app` because I think it prevented the calling the goal `war:exploded` which copies my webapp resources in the generated war. So I used instead like you mentioned the projects property in the root module.

As for the root module, I added the plugin in a DEV module so it won't have to compile twice the app module for production. So now its only purpose is to run the devmode goal.

> You can skip the gwt:generate-module and gwt:generate-module-metadata goals by setting skipModule and skipModuleMetadata properties to true.

I added these the 2 skip properties but even after reading the description [https://tbroyer.github.io/gwt-maven-plugin/generate-module-mojo.html](https://tbroyer.github.io/gwt-maven-plugin/generate-module-mojo.html) I still don't understand the purpose of these goals. Sorry !

Thank you so much for your help :+1:

**Comment by NightFox7** [comment]
One last thing before I close the issue, when I run gwt:devmode (or gwt:codeserver) goal on my root module, it executes the generate-source phase on each of my sub modules and that takes a lots of time. Is there a way to prevent that ?

**Comment by tbroyer** [comment]
> when I run gwt:devmode (or gwt:codeserver) goal on my root module, it executes the generate-source phase on each of my sub modules and that takes a lots of time. Is there a way to prevent that ?

No. We need to execute all phases up to `process-classes` to make sure we have all source roots properly added to the Maven project model. If you have goals that take a lot of time, find a way to make them "incremental" (as in: they'll do nothing if their inputs and outputs have not changed; but still add the compile source root to the Maven project model) if you control their code, or skip them (if they make it possible through a skip property).

**Comment by NightFox7** [comment]
Unfortunately, I cannot skip these goals but a couple of seconds longer won't hurt anyone. 

On the other hand, the `gwt:compile` goal seems to recompile all the gwt modules even when I change nothing. 

Shouldn'it be incremental ?

**Comment by tbroyer** [comment]
The plugin detects stale output only based on file modification time; if your goals that generate sources re-generate them each time they're run, then those sources are detected as having (potentially) changed and the module is recompiled.
If you want truly incremental builds, you'll have to use a better build tool (Gradle, Bazel, Buck, etc.), one that doesn't force each and every plugin author to write its own staleness checks (this plugin uses a library, that happens to use file mtime, and still require way too much integration work compared to other build tools)
