### ISSUE TITLE
SuperDevMode

### ISSUE THREAD

**Issue by h0ru5** [tbroyer/gwt-maven-plugin#14]
I think adding a SuperDev/Codeserver goal as in codehaus would be great for IT.

However, right now manually trying to run the codeserver fails because the generated module file is not found in the classpath. 

So, if I have my module template /src/main/module.gwt.xml, how would I start SuperDev?

Right now of course:
Loading inherited module 'it.pkg.example.Example'
   [ERROR] Unable to find 'it/pkg/example/Example.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:315)
	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:254)
	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:197)
	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:157)
	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:214)
	at com.google.gwt.dev.codeserver.Recompiler.compile(Recompiler.java:105)
	at com.google.gwt.dev.codeserver.ModuleState.<init>(ModuleState.java:58)
	at com.google.gwt.dev.codeserver.CodeServer.makeModules(CodeServer.java:120)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:95)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:71)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:49)

So first a run with gwt:generate-module is needed and then the generated module needs to be added to the classpath for the codeserver call. Or is there a better way?

**Comment by tbroyer** [comment]
`gwt:codeserver` was added in 1.0-beta-1
