### ISSUE TITLE
Missing test super source exception

### ISSUE THREAD

**Issue by branflake2267** [tbroyer/gwt-maven-plugin#50]
An exception occurs when I enable super source for test. 

I'm not sure why it occurs yet. Sometimes it throws on configuration and sometimes it doesn't. 

```
<packaging>war</packaging>

<plugin>
  <groupId>net.ltgt.gwt.maven</groupId>
  <artifactId>gwt-maven-plugin</artifactId>
  <version>${gwt.maven.plugin.version}</version>
  <extensions>true</extensions>
  <configuration>
    <!-- Eclipse will work with module naming in the gwt-app config only -->
    <moduleName>com.wrightwayeconomy.module</moduleName>
    <moduleShortName>module</moduleShortName>
    <webappDirectory>${webappDirectory}</webappDirectory>
    <launcherDir>${webappDirectory}</launcherDir>
    <startupUrls>
      <startupUrl>Project.html</startupUrl>
    </startupUrls>
  </configuration>
  <executions>
    <!-- Generate the module and add it to the webappDirectory/classes/... -->
    <execution>
      <id>generate-module</id>
      <phase>generate-resources</phase>
      <goals>
        <goal>generate-module</goal>
        <goal>add-super-sources</goal>
        <goal>add-test-super-sources</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

```
Execution generate-module of goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:add-test-super-sources failed: Unable to load the mojo 'add-test-super-sources' (or one of its required components) from the plugin 'net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5' (net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:add-test-super-sources:generate-module:generate-resources)

org.apache.maven.plugin.PluginExecutionException: Execution generate-module of goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:add-test-super-sources failed: Unable to load the mojo 'add-test-super-sources' (or one of its required components) from the plugin 'net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5'
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'add-test-super-sources' (or one of its required components) from the plugin 'net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:579)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	... 31 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.plugin.Mojo
  roleHint: net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:add-test-super-sources
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:546)
	... 32 more
Caused by: java.util.NoSuchElementException
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:118)
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:1)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 34 more

```

**Comment by branflake2267** [comment]
I think it may be crashing on my enhanced JDO source.

**Comment by branflake2267** [comment]
I think that's exactly what's happening. Datanucleus enhances the files, then when mojo executes add super sources, it crashes.

**Comment by branflake2267** [comment]
Little bit different exception, same process I think. 
```
Execution generate-module of goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:generate-module failed: Unable to load the mojo 'generate-module' (or one of its required components) from the plugin 'net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5' (net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:generate-module:generate-module:generate-resources)

org.apache.maven.plugin.PluginExecutionException: Execution generate-module of goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:generate-module failed: Unable to load the mojo 'generate-module' (or one of its required components) from the plugin 'net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5'
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:331)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1362)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl$11.call(MavenImpl.java:1)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1360)
	at org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant.build(MojoExecutionBuildParticipant.java:52)
	at org.eclipse.m2e.core.internal.builder.MavenBuilderImpl.build(MavenBuilderImpl.java:137)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:172)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$1.method(MavenBuilder.java:1)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1$1.call(MavenBuilder.java:115)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:112)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod$1.call(MavenBuilder.java:105)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:86)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:200)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:205)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:245)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:300)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:303)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:359)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:382)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'generate-module' (or one of its required components) from the plugin 'net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:579)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:121)
	... 31 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.plugin.Mojo
  roleHint: net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-5:generate-module
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:546)
	... 32 more
Caused by: java.util.NoSuchElementException
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:118)
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:1)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 34 more

```

**Comment by branflake2267** [comment]
I'm closing after finding a phase that worked. 

```
<execution>
            <id>gwt-generate</id>
            <phase>validate</phase>
            <goals>
              <goal>generate-module</goal>
              <goal>add-super-sources</goal>
            </goals>
          </execution>
```

**Comment by branflake2267** [comment]
My eclipse dev and production behave slightly differently. In production, I can't get this to work.

**Comment by branflake2267** [comment]
Hm, just as I say that, seems this is working at the moment. 
```
 <execution>
            <id>gwt-generate</id>
            <phase>intialize</phase>
            <goals>
              <goal>generate-module</goal>
              <goal>add-super-sources</goal>
            </goals>
          </execution>
```

**Comment by branflake2267** [comment]
I take that back, the issue was always there, just wasn't marked. Looks like the data nucleus is enhancing before the m2e runs. I can't seem to find a configuration that will run the goals after datanucleus. Or I'm just totally missing the issue still.

**Comment by tbroyer** [comment]
I don't get why project classes would break a Maven goal that doesn't use them; moreover it's not breaking "a Maven goal", but breaking Maven itself!
I'm afraid this must be unrelated to the plugin and rather an issue with Maven (or more probably its integration in Eclipse)

**Comment by branflake2267** [comment]
I've never seen any other maven plugin throw an exception and not sure why this one would throw it.

**Comment by tbroyer** [comment]
Googling the exception, it apparently happened to others; :

 * https://github.com/cmoulliard/droolsjbpm-osgi-examples/issues/3
 * https://vzurczak.wordpress.com/2014/07/23/another-cryptic-message-from-maven/
 * etc.

**Comment by branflake2267** [comment]
I've noticed it in other places. What I'm hoping is if I get something else solved it might go away. The exception is also obscure for me b/c I can't see the entire stack trace.

**Comment by branflake2267** [comment]
Just a note, I saw this issue pop up on war packaging. So it feels like it's definitely upstream, in some other library.
