### ISSUE TITLE
GWT Eclipse Plugin Running DevMode throws the famous jetty exception. 

### ISSUE THREAD

**Issue by branflake2267** [tbroyer/gwt-maven-plugin#65]
I don't have a handle on this classpath issue yet. This occurs when running dev mode from Eclipse. Do you know why this class path issue is occurring? 

```
Running CodeServer with parameters: [-noprecompile, -port, 9876, -sourceLevel, 1.8, -bindAddress, 127.0.0.1, -launcherDir, /Users/branflake2267/git/Archetypes/archetypes/gwt-basic/target/gwt-basic-2.0-SNAPSHOT, -logLevel, INFO, -style, OBFUSCATED, org.gonevertical.project.App]
Super Dev Mode starting up
   workDir: /var/folders/x8/9wz7qtw96t7grkdyjw1l61p40000gn/T/gwt-codeserver-7805614344613438825.tmp
2016-10-16 19:49:44.172:INFO::main: Logging initialized @2929ms
   Loading Java files in org.gonevertical.project.App.
   Module setup completed in 3175 ms
2016-10-16 19:49:45.916:INFO:oejs.Server:main: jetty-9.2.14.v20151106
2016-10-16 19:49:45.958:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletContextHandler@4a229e9d{/,null,AVAILABLE}
2016-10-16 19:49:46.219:INFO:oejs.ServerConnector:main: Started ServerConnector@52966158{HTTP/1.1}{127.0.0.1:9876}
2016-10-16 19:49:46.220:INFO:oejs.Server:main: Started @4977ms

The code server is ready at http://127.0.0.1:9876/
Code server started in 3.726 s ms
2016-10-16 19:49:46.346:INFO:oejs.Server:main: jetty-9.2.14.v20151106
Starting Jetty on port 8888
   [WARN] ServletContainerInitializers: detected. Class hierarchy: empty
2016-10-16 19:49:49.499:WARN:oejuc.AbstractLifeCycle:main: FAILED c.g.g.d.s.j.WebAppContextWithReload@4d256e0{/,file:/Users/branflake2267/git/Archetypes/archetypes/gwt-basic/target/gwt-basic-2.0-SNAPSHOT/,STARTING}{/Users/branflake2267/git/Archetypes/archetypes/gwt-basic/target/gwt-basic-2.0-SNAPSHOT}: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
    at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
    at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
    at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
    at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
    at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:550)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:759)
    at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:634)
    at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
    at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
    at com.google.gwt.dev.DevMode.main(DevMode.java:430)
2016-10-16 19:49:49.501:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.handler.RequestLogHandler@62eb0507: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
    at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
    at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
    at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
    at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
    at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:550)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:759)
    at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:634)
    at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
    at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
    at com.google.gwt.dev.DevMode.main(DevMode.java:430)
2016-10-16 19:49:49.502:INFO:oejs.ServerConnector:main: Started ServerConnector@71f3d3a{HTTP/1.1}{127.0.0.1:8888}
2016-10-16 19:49:49.502:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.Server@43c9c0b5: java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
    at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
    at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
    at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
    at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
    at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:550)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:759)
    at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:634)
    at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
    at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
    at com.google.gwt.dev.DevMode.main(DevMode.java:430)
Exception in thread "main" java.util.ServiceConfigurationError: org.apache.juli.logging.Log: Provider org.eclipse.jetty.apache.jsp.JuliLog not a subtype
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at org.apache.juli.logging.LogFactory.<init>(LogFactory.java:78)
    at org.apache.juli.logging.LogFactory.<clinit>(LogFactory.java:66)
    at org.apache.jasper.servlet.JspServlet.<init>(JspServlet.java:69)
    at org.eclipse.jetty.jsp.JettyJspServlet.<init>(JettyJspServlet.java:39)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2372)
    at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1166)
    at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1207)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:588)
    at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:396)
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:871)
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
    at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
    at com.google.gwt.dev.shell.jetty.JettyLauncher$WebAppContextWithReload.doStart(JettyLauncher.java:550)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:140)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
    at org.eclipse.jetty.server.Server.start(Server.java:387)
    at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
    at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
    at org.eclipse.jetty.server.Server.doStart(Server.java:354)
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
    at com.google.gwt.dev.shell.jetty.JettyLauncher.start(JettyLauncher.java:759)
    at com.google.gwt.dev.DevMode.doStartUpServer(DevMode.java:634)
    at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:923)
    at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
    at com.google.gwt.dev.DevMode.main(DevMode.java:430)

```

![screen shot 2016-10-16 at 7 51 36 pm](https://cloud.githubusercontent.com/assets/1326504/19424715/58909098-93e0-11e6-8047-01caf71888d1.png)

![screen shot 2016-10-16 at 7 54 55 pm](https://cloud.githubusercontent.com/assets/1326504/19424720/5eeee02a-93e0-11e6-9f87-4f4b8afdeb3f.png)

**Comment by branflake2267** [comment]
https://github.com/branflake2267/Archetypes/blob/master/archetypes/gwt-basic/pom.xml - project used

**Comment by branflake2267** [comment]
I've been at this to long today so I might be missing the simple. The video I recorded earlier it worked fine, without a hitch. The scope was set to provided and worked as expected. But further testing provided the above, but I think I might be sitting on a cache possibly.

**Comment by tbroyer** [comment]
Have a look at https://github.com/gwtproject/gwt/issues/9343, and double-check the content of your `WEB-INF/lib`; you must have `org.mortbay.jasper:apache-jsp` in there (that contains `org.apache.juli.logging.Log`); and it plays badly with our hacked `WebAppClassLoader` that would find `org.eclipse.jetty:apache-jsp` from the classpath (that contains a `META-INF/services/org.apache.juli.logging.Log` pointing to `org.eclipse.jetty.apache.jsp.JuliLog`). The `org.eclipse.jetty.apache.jsp.JuliLog` from the classpath cannot be cast to the `org.apache.juli.logging.Log` from the webapp, as the latter comes from a child classloader.

**Comment by branflake2267** [comment]
Ah, wow, I had forgotten about the web app classpath, I knew I had seen that in other configs elsewhere and figured that, but completely forgot. :) Well, I'll blame it on being tired. :) Thanks, I'll check out how that is getting loaded in the process.

**Comment by branflake2267** [comment]
Can the scope be set to provided and still have command line execution `mvn gwt:devmode` still work? Or is it expected to have no scope or a runtime scope?

**Comment by tbroyer** [comment]
Yes, absolutely. In a single module project, set all GWT dependencies' scopes as provided and set classpathScope to `compile+runtime`. See https://github.com/gwtproject/gwt/blob/master/samples/mobilewebapp/pom.xml for an example.

**Comment by bhagyalakshmisabbella** [comment]
I have given scope provided to all my dependencies. But still it is throwing jetty exception. Below is my pom.xml. Please solve this exception for me


<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

	
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.glenwood.template</groupId>
	<artifactId>template_ui</artifactId>
	<packaging>pom</packaging>
	<version>5.0-SNAPSHOT</version>
	<name>Template User Interface</name>

	<properties>
		
		<gwtVersion>2.8.0</gwtVersion>
		<glenwood-core.version>5.0-SNAPSHOT</glenwood-core.version>
		<gin.version>2.1.2</gin.version>
		<gwt.style>OBF</gwt.style>

		
		<junit.version>4.11</junit.version>
		<gwt-test-utils.version>0.44</gwt-test-utils.version>
		<jukito.version>1.3</jukito.version>
		<postgresql.version>9.1-901.jdbc4</postgresql.version>
		<jbcrypt.version>0.3m</jbcrypt.version>
		<selenium.version>2.25.0</selenium.version>
		<cucumber.version>1.0.14</cucumber.version>
		<javax.validation.version>1.0.0.GA</javax.validation.version>

		
		<gwt-maven-plugin.version>2.8.0</gwt-maven-plugin.version>
        <maven-surefire-plugin.version>2.21.0</maven-surefire-plugin.version>
        <maven-failsafe-plugin.version>2.21.0</maven-failsafe-plugin.version>
        <maven-compiler-plugin.version>3.3</maven-compiler-plugin.version>
        <maven-war-plugin.version>3.0.0</maven-war-plugin.version>
        <maven-deploy-plugin.version>2.8.2</maven-deploy-plugin.version>
        <tomcat-maven-plugin.version>2.2</tomcat-maven-plugin.version>
		<jetty-plugin.version>8.1.0.v20120127</jetty-plugin.version>

		<target.jdk>1.7</target.jdk>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<project.deployment.encoding>UTF-8</project.deployment.encoding>

		
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<project.deployment.encoding>UTF-8</project.deployment.encoding>
	</properties>

	<dependencyManagement>
		<dependencies>
			
			<dependency>
				<groupId>com.google.gwt</groupId>
				<artifactId>gwt-servlet</artifactId>
				<version>${gwtVersion}</version>
				<scope>runtime</scope>
			</dependency>
			<dependency>
				<groupId>com.google.gwt</groupId>
				<artifactId>gwt-dev</artifactId>
				<version>${gwtVersion}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>com.google.gwt</groupId>
				<artifactId>gwt-user</artifactId>
				<version>${gwtVersion}</version>
				<scope>provided</scope>
			</dependency>


			

			<dependency>
				<groupId>com.google.gwt.inject</groupId>
				<artifactId>gin</artifactId>
				<version>${gin.version}</version>
				<scope>provided</scope>
			</dependency>

			

			<dependency>
				<groupId>org.gwtbootstrap3</groupId>
				<artifactId>gwtbootstrap3</artifactId>
				<version>0.9.3</version>
			</dependency>

			

			<dependency>
				<groupId>org.gwtbootstrap3</groupId>
				<artifactId>gwtbootstrap3-extras</artifactId>
				<version>0.9.3</version>
			</dependency>


			
			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>${junit.version}</version>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>com.googlecode.gwt-test-utils</groupId>
				<artifactId>gwt-test-utils</artifactId>
				<version>${gwt-test-utils.version}</version>
				<scope>test</scope>
			</dependency>

			<dependency>
				<groupId>org.jukito</groupId>
				<artifactId>jukito</artifactId>
				<version>${jukito.version}</version>
				<scope>test</scope>
			</dependency>

			
			<dependency>
				<groupId>org.seleniumhq.selenium</groupId>
				<artifactId>selenium-java</artifactId>
				<version>2.40.0</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.seleniumhq.selenium</groupId>
				<artifactId>selenium-chrome-driver</artifactId>
				<version>2.40.0</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>org.seleniumhq.selenium</groupId>
				<artifactId>selenium-firefox-driver</artifactId>
				<version>2.40.0</version>
			</dependency>

			
			<dependency>
				<groupId>info.cukes</groupId>
				<artifactId>cucumber-core</artifactId>
				<version>1.1.3</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>info.cukes</groupId>
				<artifactId>cucumber-java</artifactId>
				<version>1.1.3</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>info.cukes</groupId>
				<artifactId>cucumber-guice</artifactId>
				<version>1.1.3</version>
				<scope>test</scope>
			</dependency>
			<dependency>
				<groupId>info.cukes</groupId>
				<artifactId>cucumber-junit</artifactId>
				<version>1.1.3</version>
				<scope>test</scope>
			</dependency>

			

			<dependency>
				<groupId>org.mindrot</groupId>
				<artifactId>jbcrypt</artifactId>
				<version>${jbcrypt.version}</version>
			</dependency>

			<dependency>
				<groupId>org.json</groupId>
				<artifactId>json</artifactId>
				<version>20090211</version>
			</dependency>
			<dependency>
				<groupId>javax.validation</groupId>
				<artifactId>validation-api</artifactId>
				<version>1.0.0.GA</version>
			</dependency>

			<dependency>
				<groupId>com.google.code.gson</groupId>
				<artifactId>gson</artifactId>
				<version>2.2.3</version>
				<scope>compile</scope>
			</dependency>

			<dependency>
				<groupId>com.googlecode.gwtphonegap</groupId>
				<artifactId>gwtphonegap</artifactId>
				<version>2.4.0.0</version>
			</dependency>

			<dependency>
				<groupId>commons-dbutils</groupId>
				<artifactId>commons-dbutils</artifactId>
				<version>1.5</version>
			</dependency>

			<dependency>
				<groupId>commons-beanutils</groupId>
				<artifactId>commons-beanutils-core</artifactId>
				<version>1.8.3</version>
			</dependency>

			
			<dependency>
				<groupId>org.mortbay.jetty</groupId>
				<artifactId>jetty-naming</artifactId>
				<version>6.1.26</version>
			</dependency>
			
			<dependency>
				<groupId>org.mortbay.jetty</groupId>
				<artifactId>jetty-plus</artifactId>
				<version>6.1.26</version>
			</dependency>

			
			<dependency>
				<groupId>org.fusesource.restygwt</groupId>
				<artifactId>restygwt</artifactId>
				<version>2.2.0</version>
			</dependency>

			
			<dependency>
				<groupId>javax.ws.rs</groupId>
				<artifactId>javax.ws.rs-api</artifactId>
				<version>2.0</version>
			</dependency>

			
			<dependency>
				<groupId>postgresql</groupId>
				<artifactId>postgresql</artifactId>
				<version>9.1-901.jdbc4</version>
			</dependency>

			
			<dependency>
				<groupId>com.allen-sauer.gwt.dnd</groupId>
				<artifactId>gwt-dnd</artifactId>
				<version>3.1.2</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
					<configuration>
						<source>${target.jdk}</source>
						<target>${target.jdk}</target>
						<encoding>${project.build.sourceEncoding}</encoding>
						<proc>none</proc>
					</configuration>
				</plugin>

				
				
				
				
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>gwt-maven-plugin</artifactId>
					<version>${gwt-maven-plugin.version}</version>
					<configuration>
						<gwtSdkFirstInClasspath>true</gwtSdkFirstInClasspath>

						<strict>true</strict>
						<testTimeOut>180</testTimeOut>
						
						<includes>**/*GwtTest.java</includes>
						
						<mode>htmlunit</mode>

						<extraJvmArgs>-Xss1024K -Xmx1024M</extraJvmArgs>
						<logLevel>INFO</logLevel>
						<style>${gwt.style}</style>

						<copyWebapp>true</copyWebapp>
						<hostedWebapp>${webappDirectory}</hostedWebapp>

						<compileReport>true</compileReport>
						<runTarget>template.html</runTarget>
						
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>compile</goal>
								<goal>test</goal>
								
								<goal>generateAsync</goal>
							</goals>
						</execution>
					</executions>
					


				</plugin>

				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>${maven-deploy-plugin.version}</version>
					<configuration>
						<skip>true</skip>
					</configuration>
				</plugin>

				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-war-plugin</artifactId>
					<version>${maven-war-plugin.version}</version>
					<executions>
						<execution>
							<phase>compile</phase>
							<goals>
								<goal>exploded</goal>
							</goals>
						</execution>
					</executions>
					<configuration>
						<webappDirectory>${webappDirectory}</webappDirectory>
					</configuration>
				</plugin>

				
				
				
				
				<plugin>
					<groupId>org.apache.tomcat.maven</groupId>
					<artifactId>tomcat7-maven-plugin</artifactId>
					<version>${tomcat-maven-plugin.version}</version>
					<configuration>
						
						<server>arcbees-tomcat</server>
						<path>${tomcat.path}</path>
						<url>${tomcat.server.url}</url>
						<update>true</update>
					</configuration>
					<executions>
						<execution>
							<phase>deploy</phase>
							<goals>
								<goal>deploy</goal>
							</goals>
						</execution>
					</executions>
				</plugin>

				
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-failsafe-plugin</artifactId>
					<version>${maven-failsafe-plugin.version}</version>
					<executions>
						<execution>
							<id>integration-test</id>
							<phase>integration-test</phase>
							<goals>
								<goal>integration-test</goal>
							</goals>
							<configuration>
								<includes>
									<include>**/*TestInt.java</include>
								</includes>
							</configuration>
						</execution>
						<execution>
							<id>verify</id>
							<phase>verify</phase>
							<goals>
								<goal>verify</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<modules>
		<module>template_ui_core</module>
		<module>template_ui_mobile</module>
		<module>template_ui_tablet</module>
		<module>template_ui_desktop</module>
	</modules>
</project>

**Comment by tbroyer** [comment]
> Please solve this exception for me

:astonished: 

Anyway, you're not using this gwt-maven-plugin, but https://gwt-maven-plugin.github.io/gwt-maven-plugin/
