### ISSUE TITLE
"mvn jetty:run" fails with IllegalArgumentException

### ISSUE THREAD

**Issue by foxylion** [tbroyer/gwt-maven-plugin#77]
I'm using mvn 3.3.9 with JDK 1.8.0_121 on Ubuntu 16.04.

When creating the sample from the maven archetype and trying to start the server it fails with the following stack trace:
```
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@6535117e{/,file:///home/jj/Files/gwt-test/swid/swid-server/src/main/webapp/,null}{file:///home/jj/Files/gwt-test/swid/swid-server/src/main/webapp/}
java.lang.IllegalArgumentException: file:///home/jj/Files/gwt-test/swid/swid-server/target/tmp/1 is not an existing directory.
at org.eclipse.jetty.util.resource.ResourceCollection.<init>(ResourceCollection.java:88)
at org.eclipse.jetty.maven.plugin.MavenWebInfConfiguration.unpack(MavenWebInfConfiguration.java:180)
at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
at org.eclipse.jetty.maven.plugin.MavenWebInfConfiguration.preConfigure(MavenWebInfConfiguration.java:95)
at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
at org.eclipse.jetty.maven.plugin.JettyWebAppContext.doStart(JettyWebAppContext.java:398)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131)
at org.eclipse.jetty.server.Server.start(Server.java:422)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105)#
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
at org.eclipse.jetty.server.Server.doStart(Server.java:389)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:460)
at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:328)
at org.eclipse.jetty.maven.plugin.JettyRunMojo.execute(JettyRunMojo.java:170)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

I created the project using `mvn archetype:generate -DarchetypeCatalog=https://oss.sonatype.org/content/repositories/snapshots/ -DarchetypeGroupId=net.ltgt.gwt.archetypes -DarchetypeArtifactId=modular-webapp -DarchetypeVersion=1.0-SNAPSHOT`.

**Comment by foxylion** [comment]
Okay, the `mvn jetty:run` is working with Maven 3.2.1, but then I've to call `mvn install` before, otherwise the call fails with `[ERROR] Failed to execute goal on project swid-server: Could not resolve dependencies for project swgroup:swid-server:war:1.0-SNAPSHOT: Could not find artifact swgroup:swid-client:war:1.0-SNAPSHOT in nexus (http://xnexus:8081/content/groups/public) -> [Help 1]`.

**Comment by tbroyer** [comment]
This is called out in the tbroyer/gwt-maven-archetypes README, and is a limitation of the jetty-maven-plugin (and of Maven). I have no idea why it fails with Maven 3.3.9 and works with Maven 3.2.1, but please open an issue on tbroyer/gwt-maven-archetypes if you reliably reproduce (when following the README instructions to the letter).
